### ISSUE TITLE
Support for mongo java driver v4.0+

### ISSUE THREAD

**Issue by juja0** [cloudyrock/mongock#157]
I'm using mongock in my dropwizard project which already uses mongodb-driver-sync v4.0

When I add mongock-core v3.2.8 to my codebase, some of my existing tests break with the following error.

java.lang.NoSuchMethodError: 'com.mongodb.client.result.InsertOneResult com.mongodb.client.MongoCollection.insertOne(java.lang.Object)'

As described in the 'known issues' section, if I exclude 'mongo-java-driver' from 'mongock-core', my existing tests work fine but the one I wrote to test migration fails with the following error.

java.lang.NoSuchMethodError: 'void com.mongodb.client.MongoCollection.insertOne(java.lang.Object)'
 
Problem seems to stem from the fact that the signature of 'com.mongodb.client.MongoCollection.insertOne' has changed between java driver v3 and v4

The point of failure is at this line
	com.github.cloudyrock.mongock.ChangeEntryMongoRepository.save(ChangeEntryMongoRepository.java:26)
 
where there's an explicit call to 'collection.insertOne' which uses MongoCollection from the v3 driver (presumably since mongock is compiled using the v3 driver).

I couldn't come up with a clean solution to solve this without either creating a fresh project just for migrations or creating custom implementations of classes like ChangeEntryMongoRepository. Just wanted to see what your thoughts are on this. Anything I've missed that I should try out or is it possible to add support for v4 on mongock-core ? 

Thanks for the great library.

**Comment by dieppa** [comment]
Hi @juja0 ,

first thanks for your feedback.
We are currently working on **Mongock V4.0**(while obviously maintaining V3.X). In this version we are not only providing new features, also refactoring it in such a way that it's split in modules. The part that is dealing with the package processor, framework,  etc. is called runner(standalone, spring, etc.) and the persistence side, driver(Mongo driver V3.x, Mongo Driver V4.x, ElasticSearch, etc.). I say all that for you to have a bit of context and understand that makes easier to provide a potential solution to your issue.

Anyway, We were thinking to provide an alpha version. It's alpha because we want people to start testing it while adding more features, but the existing features are pretty stable. Although right now we only provide support for Mongock 3.x and EaslticSearch(from a big client's request), I could think on some options to solve your issue. But I would need first to have a bit more information:

1) Type of project
2) How big is your project
3) In which development phase your product currently(poc, development, pre-production, production...)
3) Does your team have resources to do a potential PR yourself?
4) How urgent is this for you? Could you wait 2 weeks?

With that information, I am sure we can provide a good solution :)

Thanks

**Comment by juja0** [comment]
Thanks for the quick reply :)

Splitting by persistence type makes sense. To your questions,

1. It's a dropwizard based server side application which exposes certain REST APIs and saves application specific metadata in a mongo database. It's a POC for a financial application that's being built as part of a startup that's still in the brainstorming stage.
2. It's not very big. I just started working on it. It has around 8000 LOC at the moment.
3. It's in the POC phase.
4. It's just me right now and yes I can contribute if required :)
5. It's not urgent. I was able to get it to work for now by copying ChangeEntryMongoRepository verbatim into my codebase. Since it's in my codebase, it gets compiled against the v4 driver and works fine. I can definitely wait 2 weeks.

Regards,

**Comment by dieppa** [comment]
Thanks, for the information @juja0. So knowing that, I would try to provide an alpha version for you as soon as we can. It's good for us to have someone testing it too.

If you can provide your email, so I can keep you updated, would be good.

**Comment by murdos** [comment]
Hi @dieppa 

I'm currently working on upgrading JHipster for the upcoming Spring Boot 2.3, which means also updating Spring Data MongoDB to 3.0 and using the MongoDB Java Driver 4.x.
We're currently using mongobee, but since it's not maintained, I'm investigating moving to mongock.
So I would also be interested by an alpha or beta version.

**Comment by juja0** [comment]
Thanks @dieppa . I'm not sure how to send you a private message. Would it be ok if I sent my email ID over to the dev distro at cloudyrock.io ?

**Comment by dieppa** [comment]
@juja0 , sure, send it to dev@cloudyrock.io

**Comment by dieppa** [comment]
@murdos , that's great. Not only Mongobee is not maintained long time ago, it miss a lot things, some of them pretty basic for a comercial application.

Anyway, happy to keep you in the list. Please send me your email id to dev@cloudyrock.io and we'll keep you updated too.

Just one thing, I might be missing something, but as long as I am aware version 2.2.7.RELEASE is the latest spring-data-mongodb version. Please correct me if I am wrong.


Also it would be great if you can fill this [survey](https://forms.gle/uk9jmtKvxJzi5Bda7), which takes just one minute and helps us a lot.

[Mongock V4.0 roadmap](https://github.com/cloudyrock/mongock/blob/v3/README.md#version-40)

Thanks

**Comment by murdos** [comment]
> Anyway, happy to keep you in the list. Please send me your email id to dev@cloudyrock.io and we'll keep you updated too.

I will do it, thanks.

> Just one thing, I might be missing something, but as long as I am aware version 2.2.7.RELEASE is the latest spring-data-mongodb version. Please correct me if I am wrong.

I'm working with 3.0.0.RC2, anticipating the upcoming release (in one or two weeks).

**Comment by juja0** [comment]
> @juja0 , sure, send it to [dev@cloudyrock.io](mailto:dev@cloudyrock.io)
> 
> Also it would be great if you can fill this [survey](https://forms.gle/uk9jmtKvxJzi5Bda7), which takes just one minute and helps us a lot.

Done and done.

Thanks.

**Comment by dieppa** [comment]
provided alpha versions. Anything, please create a new issue

**Comment by aggo** [comment]
Hi, what version of this lib should I use that works with java driver v4.0?

**Comment by dieppa** [comment]
Hello @aggo ,

take a look to this [documentation](https://www.mongock.io/quick-start), which is still under development. But I think it will resolve your questions. 

Please let me know any question or suggestion you might have.

**Comment by aggo** [comment]
Thank you @dieppa for the fast answer :) our problem was that we didn't manage to run our tests anymore, relevant error being:

``` com.mongodb.client.result.InsertOneResult com.mongodb.client.MongoCollection.insertOne(java.lang.Object)

java.lang.NoSuchMethodError: 'com.mongodb.client.result.InsertOneResult com.mongodb.client.MongoCollection.insertOne(java.lang.Object)
```
I included the libs as described in the documentation you suggested and removed an extra dependency to mongodb-java-driver that we had and now things work as expected.
Kudos for the good job with the lib! ^^

**Comment by aggo** [comment]
@dieppa Please let me know at amaliagoia@gmail.com when a new release of the lib is ready, if you have time. Thank you once again!
